# USB port
port: /dev/ttyUSB0
# Tf frame id
frame_id: imu_bosch_link
# Data reading frequency
freqency: 200
# Sensor operation mode --> modes could be found in sensor datasheet
operation_mode: 0x08
axis_map: 0x21 # Z=z, X=y, Y=x
axis_map_sign: 0x00 # -X,-Y,-Z 
